import { ENGINE_IDS, runEngine } from "./qengine.mjs";
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];let active="QP-01",lastResult=null;const nonceStore=new Set();
const titles={"QP-01":"Point Engine","QR-01":"Resonance Engine","QG-01":"Geometry Transition Engine","QA-01":"Axis Gate Engine","QC-01":"Chronos Engine","QI-01":"Invariant & Provenance Engine"};
function examples(id){const now=new Date(),expires=new Date(now.getTime()+300000);const common={operationId:"demo-"+id.toLowerCase()+"-"+Date.now()};if(id==="QP-01")return[{...common,object:"Публичный выпуск",innerConfiguration:"Авторская ось",position:"точка запуска",attention:"удержано",geometry:"Gᴱ"},{},{requireDistinctComponents:true}];if(id==="QR-01")return[{...common,subjectStructure:"явное намерение автора",fieldStructure:"предъявленный отклик группы",point:"O ⊕ I",geometry:"Gᴿ",criteria:[{id:"c1",match:true},{id:"c2",match:true}],metrics:{alpha:.75,iy:.75,cm:.75,q:.75,t:.75},profile:"TX3",requiredLoad:1,proposedForm:"совместный следующий ход"},{},{allowedProfiles:["TX3"],containerCapacity:2,minimumMatch:.75}];if(id==="QG-01")return[{...common,construct:"авторский конструкт",sourceGeometry:"Gᴱ",targetGeometry:"Gᴾ",representationProfile:"visual-rendering",invariantCriterion:"сохраняется авторская ось",transitionRule:"Tᴱᴾ",targetForm:"проективное представление",invariantEvidence:["passport:demo"],transitionCount:1},{preflightInvariantVerdict:"preserved"},{allowedTransitions:["Gᴱ→Gᴾ"],transitionBudget:1}];if(id==="QA-01")return[{...common,subjectRef:"subject:pseudonymous-demo",role:"author",operation:"read",scope:"public-corpus",axisCriteria:[{id:"intent-declared",met:true}]},{authenticationEvidence:{verified:true,provider:"external-demo"},axisEvidence:[]},{allowedRoles:["author"],allowedOperations:["read"],allowedScopes:["public-corpus"],explanationProtocol:"axis-gate-demo-v1"}];if(id==="QC-01")return[{...common,phase:"arm",timeSource:"browser-demo",issuedAt:now.toISOString(),expiresAt:expires.toISOString(),nonce:"nonce-"+Date.now(),idempotencyKey:"idem-"+Date.now()},{cleanupHandlerId:"browser-session-cleanup"},{trustedTimeSources:["browser-demo"],maxClockSkewMs:5000,maxTtlMs:600000}];return[{...common,invariant:"авторская ось сохранена",author:"Александр Лацинник",version:"0.2.0",source:"TZAR-QENGINE-001",seal:"external-seal-reference",signature:"external-signature-reference",provenance:["TZAR-DECLARATION-001","TZAR-AXIOM-001"],invariantCriteria:[{id:"sigma",verdict:"preserved"}]},{integrityEvidence:{sealVerified:true,signatureVerified:true,signerTrusted:true}},{requireSignature:true,compatibleVersions:["0.2.0"]}]}
function renderNav(){$("#engine-nav").innerHTML=ENGINE_IDS.map(id=>'<button data-engine="'+id+'" class="'+(id===active?"active":"")+'"><span>'+id+'</span><small>'+titles[id]+'</small></button>').join("");$$('[data-engine]').forEach(button=>button.addEventListener("click",()=>{active=button.dataset.engine;renderNav();loadExample()}))}
function loadExample(){const [request,context,policy]=examples(active);$("#engine-title").textContent=active+" · "+titles[active];$("#request").value=JSON.stringify(request,null,2);$("#context").value=JSON.stringify(context,null,2);$("#policy").value=JSON.stringify(policy,null,2);$("#summary").className="empty";$("#summary").textContent="Эталонный вход загружен. Измените или исполните его.";$("#result").textContent="";lastResult=null;$("#export").disabled=true;$("#status").textContent="fail-closed контур готов"}
function readJson(selector){try{return JSON.parse($(selector).value)}catch(error){throw new Error(selector.slice(1)+": "+error.message)}}
function run(){try{const request=readJson("#request"),context=readJson("#context"),policy=readJson("#policy");lastResult=runEngine(active,request,context,policy,{nonceStore});$("#result").textContent=JSON.stringify(lastResult,null,2);$("#summary").className="summary "+lastResult.outcome;$("#summary").innerHTML='<span>'+lastResult.outcome.toUpperCase()+'</span><div><b>'+lastResult.engineId+' · '+lastResult.lifecycleState+'</b><p>Invariant: '+lastResult.invariantVerdict+(lastResult.error?' · '+lastResult.error.code:' · structured result returned')+'</p></div>';$("#status").textContent=lastResult.outcome+" · "+lastResult.invariantVerdict;$("#export").disabled=false}catch(error){lastResult=null;$("#summary").className="summary failed";$("#summary").innerHTML='<span>INPUT</span><div><b>JSON не исполнен</b><p>'+error.message+'</p></div>';$("#result").textContent="";$("#export").disabled=true}}
function exportResult(){if(!lastResult)return;const blob=new Blob([JSON.stringify(lastResult,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="qengine-"+lastResult.operationId+".json";link.click();URL.revokeObjectURL(url)}
$("#load-example").addEventListener("click",loadExample);$("#run").addEventListener("click",run);$("#export").addEventListener("click",exportResult);renderNav();loadExample();
