import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { example } from "./example.mjs";
import { extractInvariant, verifyPayload, verifyReportSeal } from "./core.mjs";
import { buildSemanticItems, chunkSemanticText, classifySemantic, cosineSimilarity, detectLogicRisks, inspectAnchors, lexicalDifference, meanNormalizedVector, parseAnchors, SEMANTIC_MODEL_REVISION } from "./semantic.mjs";
import { buildAuthorReview, calibrationSummary, validateCalibrationCorpus } from "./calibration.mjs";

const report = await verifyPayload(example);
assert.equal(report.pass, true);
assert.equal(report.positive.length, 3);
assert.ok(report.positive.every((item) => item.pass));
assert.equal(report.negative.length, 1);
assert.equal(report.negative[0].pass, true);
assert.equal(new Set(report.positive.map((item) => item.hash)).size, 1);
assert.notEqual(report.positive[0].hash, report.negative[0].hash);
assert.equal(report.positive[0].differences.length, 0);
assert.equal(report.negative[0].differences[0].field, "axisDefinition");
assert.equal(report.ledger.length, 3);
assert.ok(report.ledger.every((entry) => entry.continuous));
assert.equal(report.firstBreak, null);
assert.equal((await verifyReportSeal(report)).valid, true);
assert.equal(new Set(report.ledger.map((entry) => entry.transitionHash)).size, 3);
assert.throws(() => extractInvariant({ invariant: { constructId: "broken" } }), /author/);

const broken = structuredClone(example);
broken.forms[1].invariant.axisDefinition = "Подмена";
assert.equal((await verifyPayload(broken)).pass, false);
const brokenReport = await verifyPayload(broken);
assert.equal(brokenReport.firstBreak.index, 2);
assert.equal(brokenReport.ledger[2].continuous, false);
const tamperedPassport = structuredClone(report);
tamperedPassport.positive[0].label = "Подменённая форма";
assert.equal((await verifyReportSeal(tamperedPassport)).valid, false);
assert.equal((await verifyReportSeal({})).valid, false);

assert.deepEqual(parseAnchors("  Осевой термин  \nосевой термин\nВторая опора"), ["осевой термин", "вторая опора"]);
assert.equal(inspectAnchors("Здесь есть ОСЕВОЙ   ТЕРМИН.", ["осевой термин"]).coverage, 1);
assert.deepEqual(inspectAnchors("Опора утрачена", ["осевой термин"]).missing, ["осевой термин"]);
assert.equal(cosineSimilarity([1, 0], [1, 0]), 1);
assert.equal(cosineSimilarity([1, 0], [0, 1]), 0);
assert.throws(() => cosineSimilarity([1], [1, 2]), /одинаковую/);
assert.equal(classifySemantic(0.9, inspectAnchors("опора", ["опора"])).code, "preserved");
assert.equal(classifySemantic(0.7, inspectAnchors("опора", ["опора"])).code, "review");
assert.equal(classifySemantic(0.4, inspectAnchors("опора", ["опора"])).code, "rupture");
assert.equal(classifySemantic(0.99, inspectAnchors("другой текст", ["опора"])).code, "critical-break");
const semanticItems = buildSemanticItems("Источник", [{ label: "A", text: "опора" }], [[1, 0], [0.8, 0.2]], ["опора"]);
assert.equal(semanticItems.length, 1);
assert.equal(semanticItems[0].verdict.code, "preserved");
assert.equal(detectLogicRisks("Теория может работать", "Теория может работать").length, 0);
const negationRisk = detectLogicRisks("Метод работает", "Метод не работает");
assert.equal(negationRisk[0].code, "negation");
assert.equal(negationRisk[0].severity, "critical");
assert.ok(detectLogicRisks("Это гипотеза", "Это доказанный факт").length >= 2);
assert.deepEqual(lexicalDifference("осевой термин сохраняется", "осевой термин исчезает").removed, ["сохраняется"]);
assert.deepEqual(lexicalDifference("осевой термин сохраняется", "осевой термин исчезает").added, ["исчезает"]);
assert.equal(chunkSemanticText("Короткий текст.").length, 1);
assert.equal(chunkSemanticText("а".repeat(1000), 400).length, 3);
assert.equal(chunkSemanticText("Первая мысль. Вторая мысль.", 18).length, 2);
assert.deepEqual(meanNormalizedVector([[1, 0], [1, 0]]), [1, 0]);
const logicalItem = buildSemanticItems("Метод работает", [{ label: "Инверсия", text: "Метод не работает" }], [[1, 0], [1, 0]], []);
assert.equal(logicalItem[0].verdict.code, "logical-risk");
assert.equal(logicalItem[0].logicRisks[0].code, "negation");
assert.equal(SEMANTIC_MODEL_REVISION.length, 40);

const corpus = JSON.parse(await readFile(new URL("./calibration/corpus.v1.json", import.meta.url), "utf8"));
const corpusCheck = validateCalibrationCorpus(corpus);
assert.equal(corpusCheck.valid, true);
assert.equal(corpusCheck.caseCount, 12);
assert.equal(new Set(corpus.cases.map((item) => item.id)).size, 12);
assert.equal(corpus.cases.filter((item) => item.candidateLabel === "preserved").length, 4);
assert.equal(corpus.cases.filter((item) => item.candidateLabel === "review").length, 4);
assert.equal(corpus.cases.filter((item) => item.candidateLabel === "rupture").length, 4);
const twoDecisions = { [corpus.cases[0].id]: "preserved", [corpus.cases[1].id]: "rupture" };
assert.equal(calibrationSummary(corpus, twoDecisions).reviewed, 2);
assert.equal(calibrationSummary(corpus, twoDecisions).complete, false);
assert.equal(buildAuthorReview(corpus, twoDecisions).status, "author-review-draft");
const allDecisions = Object.fromEntries(corpus.cases.map((item) => [item.id, item.candidateLabel]));
assert.equal(calibrationSummary(corpus, allDecisions).complete, true);
assert.equal(calibrationSummary(corpus, allDecisions).agreementRate, 1);
assert.equal(buildAuthorReview(corpus, allDecisions).status, "author-reviewed");

console.log("TZAR-PRODUCT-001: 58 assertions passed");
